# Generated by Django 4.2.27 on 2026-02-02 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content_based', 'Content-Based'), ('hybrid', 'Hybrid'), ('trending', 'Trending'), ('personalized', 'Personalized')], default='personalized', max_length=20)),
                ('score', models.FloatField(help_text='Recommendation confidence score (0-1)')),
                ('reason', models.TextField(blank=True, help_text='Explanation for why this movie is recommended')),
                ('is_clicked', models.BooleanField(default=False, help_text='Whether user clicked on this recommendation')),
                ('is_rated', models.BooleanField(default=False, help_text='Whether user rated this recommended movie')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('not_interested', 'Not Interested')], max_length=20)),
                ('comment', models.TextField(blank=True, help_text='Optional user comment')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
